server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 文件上传 设置文件大小， 即最大的尺寸
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    # mybatis-plus 日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag  #逻辑删除字段  （数据库中逻辑删除字段用delFlag）
      logic-delete-value: 1       # 删除值 1
      logic-not-delete-value: 0   # 未删除值 0
      id-type: auto             #主键自增（不设置用 mybatis-plus默认生成的id）
#  当用maven导入了mybatisplus的包时，必须要在yml配置中配置数据库的参数，否则运行boot启动类会报错

#自定义格式， key: value    :后面必须要有空格
oss:
  accessKey: 7R0PVHVZqQ_9ZUc65kwtYzjZhB5DhtMczhS6822g
  secretKey: mTF-oazwPEHvO5FnQXFoWPRXKWjSmvC_55Ysycxb
  bucket: pk-sg-blog